name: Build MacOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到最新版本

      - name: Set up Python
        uses: actions/setup-python@v5  # 升级到最新版本
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # 安装 PyInstaller

      - name: Build MacOS app
        run: |
          source venv/bin/activate
          pyinstaller --windowed --onefile --name=MyApp remove_transparency.py  # 使用 PyInstaller 打包
          ls -R dist  # 递归列出 dist 目录内容，检查生成的文件

      - name: Upload .app file
        uses: actions/upload-artifact@v4  # 使用最新版本
        with:
          name: MyApp
          path: dist/**/*.app  # 递归匹配所有子目录中的 .app 文件
